server:
  port: 8081

spring:
  application:
    name: kafka-consumer-basic
  
  kafka:
    bootstrap-servers: localhost:9092
    
    # 기본 컨슈머 설정 - 카프카 핵심 가이드 p.120-140 참조
    consumer:
      # 기본 설정
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
      # 그룹 ID 설정
      group-id: basic-consumer-group
      
      # 오프셋 리셋 정책 - 카프카 핵심 가이드 p.127
      auto-offset-reset: earliest
      
      # 자동 커밋 설정 - 카프카 핵심 가이드 p.128
      enable-auto-commit: true
      auto-commit-interval: 5000ms
      
      # 세션 타임아웃 설정
      session-timeout: 30000ms
      heartbeat-interval: 3000ms
      
      # 메시지 가져오기 설정
      fetch-min-size: 1
      fetch-max-wait: 500ms
      max-poll-records: 500
      
      # 연결 설정
      reconnect-backoff: 50ms
      retry-backoff: 100ms
      
      # 고급 설정
      max-poll-interval: 300000ms  # 5분
      request-timeout: 30000ms
      
      # 파티션 할당 전략 - 카프카 핵심 가이드 p.135
      partition-assignment-strategy: org.apache.kafka.clients.consumer.RangeAssignor

logging:
  level:
    org.apache.kafka: INFO
    team.sipe.antcode97.consumerbasic: DEBUG
    org.springframework.kafka: DEBUG 