server:
  port: 8090

spring:
  application:
    name: kafka-producer
  
  kafka:
    bootstrap-servers: localhost:9092
    
    # 프로듀서 설정 - 카프카 핵심 가이드 p.85-95 참조
    producer:
      # 기본 설정
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      # 성능 최적화 설정
      batch-size: 16384                    # 배치 크기 (16KB)
      buffer-memory: 33554432              # 버퍼 메모리 (32MB)
      compression-type: snappy              # 압축 타입 (snappy가 가장 빠름)
      linger-ms: 5                         # 배치 대기 시간
      
      # 신뢰성 설정
      acks: all                            # 모든 복제본에서 확인
      retries: 3                           # 재시도 횟수
      enable-idempotence: true             # 멱등성 보장
      
      # 고급 설정
      max-in-flight-requests-per-connection: 5  # 연결당 최대 요청 수
      request-timeout-ms: 30000            # 요청 타임아웃
      delivery-timeout-ms: 120000          # 전송 타임아웃
      
      # 압축 설정 (위에서 이미 정의됨)
      
      # 파티션 전략
      partitioner-class: org.apache.kafka.clients.producer.internals.DefaultPartitioner

logging:
  level:
    org.apache.kafka: INFO
    team.sipe.antcode97.producer: DEBUG
    org.springframework.kafka: DEBUG 